import type { Metadata } from "next";
import "@/app/globals.css";
import "@/app/assest/colors.css";

export const metadata: Metadata = {
  title: "Default layout",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {


  return (
    <html lang="en">
      <body
        className="antialiased font-nunito"
        suppressHydrationWarning={true}
      >  
          {children}
      </body>
    </html>
  );
}
